server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 301 /docs-site/;
    }

    location /docs-site/ {
        try_files $uri $uri/ =404;
    }

    location /dist/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /docs-site/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
